# Generated by Django 4.2.11 on 2024-07-09 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_posts_name_post_alter_posts_posts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='category',
        ),
        migrations.AddField(
            model_name='subscription',
            name='Category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='news.postcategory'),
            preserve_default=False,
        ),
    ]
